export { createConsoleSink } from './console.js'
export type { Options as ConsoleSinkOptions } from './console.js'
export { createFileSink, type Options as FileSinkOptions } from './file.js'
export { isSink } from './sink.js'
export type { Sink } from './sink.js'
