export { createConsoleSink } from './console.ts'
export type { Options as ConsoleSinkOptions } from './console.ts'
export { createFileSink, type Options as FileSinkOptions } from './file.ts'
export { isSink } from './sink.ts'
export type { Sink } from './sink.ts'
