name: Node.js Publish
on:
  release:
    types: [published]

env:
  NODE_VERSION: 16.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Version
        run: yarn version --new-version "${GITHUB_REF:11}" --no-git-tag-version
      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
